spring:
  application:
    name: stuti
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(2LAzrkyBceryYo7GJs8UjMYb77WeR6OUzR7hsbisSVDvQH/kvcV98otq2n6o9i7J9bFz/zyyJUv/rs3DcJkDGkdJkwFJnt85n6OjbyR8r+ncXq+7RElwfA==)
            client-secret: ENC(TRmqKnX2qYZ1igV8hzj3Am0xfRSAfx9e6owqC7QOgVDBZHriSlApP4LhIdWILq11)
            scope: [ profile, email ]
            redirect-uri: http://www.medigo.p-e.kr/login/oauth2/code/google
app:
  jwt:
    header: token
    issuer: medigo
    tokenSecret: ENC(dXvHOGQ6PnIikz0x1NLfW+j3PoWKEL5o0eVAGn8sam/VoqTTE83W3vWlZB+1KcWt)
    tokenExpiry: 3600000
    refreshTokenExpiry: 172800000
  mydata:
    encspec: ENC(NrlqiyVzuIa+tWCN/sm9Pslcq6WUYawnw9YVVkqhaio=)
    enckey: ENC(pGVuAVnTG03EzPMFR8iuCSdnvkSOUk1pQxZyh7IPylBSM6B0ZMwibS6sRuTyBV0o)
    enciv: ENC(NeJQjRk5zTblHpSGv3Y5dD5zHW85YHyp7OZjpe6rAt8=)
    token: ENC(/T1bGmFJlY/9xM1nPOxwW5eb8bogtLVE0wL5IakIj6JRZgMX2SBqPQEcZBTyCIXVlQwoznD6E6o=)
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,PATCH,DELETE
    allowed-headers: '*'
    max-age: 3600
  oauth:
    domain: "http://localhost:3000"
    signupPath: "/signup"
    signupTime: 300
    loginSuccessPath: "/main"
