name: medigo-deploy-1.0.0

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t spring-cicd .
        docker tag medigo dldydgns53/medigo:${GITHUB_SHA::7}
        docker push dldydgns53/medigo:${GITHUB_SHA::7}


    - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_DNS }}
          username: ec2-user
          key: ${{ secrets.SSH_KEYGEN_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull dldydgns53/medigo:${GITHUB_SHA::7}
            docker tag dldydgns53/medigo:${GITHUB_SHA::7} dldydgns53
            docker stop server
            docker run -d --rm --name server -p 80:8080 dldydgns53